sudo: required

language: java

services:
  - docker

script:
  - docker build -t share-microservice .
after_success:
  - docker tag share-microservice "$DOCKER_HUB_USERNAME"/share-microservice:latest
  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  - docker push "$DOCKER_HUB_USERNAME"/share-microservice:latest