kumuluzee:
  name: share-service
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  health:
    checks:
      mongo-health-check:
        connection-url: mongodb://rso-mongo-service:27017/local?serverSelectionTimeoutMS=2000